version: 2
jobs:
  dockerbuild:
    docker:
      - image: cimg/python:3.7.12 
    steps:
      - checkout
      - run:
          name: install aws
          command: |
            sudo apt-get install pip3
            sudo pip3 install awscli
      - run:
          name: "export env var."
          command: |
            export AWS_ACCESS_KEY_ID="ASIA2DYVJGKZWUBTOE7B"
            export AWS_SECRET_ACCESS_KEY="qIgi8anT6NsvkJukVx0pOLuQtUa6zWdjkkv3PWR3"
            export AWS_SESSION_TOKEN="IQoJb3JpZ2luX2VjEFAaCXVzLWVhc3QtMSJHMEUCIHQ5DoDgkl1JM+GzT4xfvXbmhXMjH1GJmF149eepyLZgAiEA+gZvHgWITFGQfRGzBaGUQRZY9NpWiDZg7hkFUpjpPYAqjAMIqf//////////ARADGgw2OTUyOTI0NzQwMzUiDEojTTTFl+U367CwSirgAulti5k986v1VkeuEKDVhmliIz0d3UUjwTAOXTM2VoTvydmblbH6SiVbihDsY7fRu9ohjad3tlQxajVvGddcudHHkH4j1gYQkbhhcWa8jWX/UBdzQFkuoeN45NUuFsBENYgNItGlnS59oOblGybinpTZOl3mPyNznkG8bsM1TNTNRoViWibMaHdQ0qLncTx9bbH+EDF1MTsUZ66sC+ACymwZ+0hqHiQGc4m8w+WjcU7BrGC0xvPVXk2XQUOroDQ7v/7QyIlyG6toJG5e0gIOS/ax7T4ktr/2eLiSBAv5KDkyielH5QR7BgOv66s8xVsP7nGRbuH64oUKxDKKmfWWPHLIUsu1X9VH4XMqoiEqQR4aHL8/jZhQVpDQSnhvVSQusr8K3pA/PuevA23xjRP1GxSFEVPbHmnD60UGTSgnllSxP0ga1cqhvXE760RVJo1sFgcugTFBQCPnzOoPMc03sqMwqvvjkAY6pgElLQ9KyzMj+HHgOM1kRRV5dt3P2MWk45Y91TeMOdtp0tK3C9C1kkLSKRSKCzlK5at9lsJMX1R5ClWkdE1Cm3QdnXisQ1Xks5wAeLhsOfngJhWa0GaZUR/DA+wP1t6n40h5K8Uf29bfnH/pngZq3Fn0XEwSUuZJLgR4qpNCa0wFI2xXSTogA34HwyxT99EB4NnGcwrmhpwxnQcgZ0acTDkXIzugWdOb"
      - run:
          name: "Log in to AWS ECR"
          command: eval $(aws ecr get-login --region $REGION --no-include-email)
      - run:
          name: Build and push Docker image
          command: |
            sha=$CIRCLE_SHA1
            TAG=latest
            docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/mclouds-prod-ecr:latest .
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/mclouds-prod-ecr:$TAG
  deployecs:
    machine: true
    steps:
      - run:
          name: install aws & ecs-deploy
          command: |
            curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
            unzip awscli-bundle.zip
            sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
            sudo wget "https://raw.githubusercontent.com/silinternational/ecs-deploy/develop/ecs-deploy" -O /usr/local/bin/ecs-deploy
            sudo chmod +x /usr/local/bin/ecs-deploy
      - run:
          name: deploying to ECS
          command: |
            sha=$CIRCLE_SHA1
            TAG=latest
            echo "ecs-deploy --region $REGION --cluster $CLUSTER --service-name $SERVICE --image $AWS_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/chat-demo:$TAG --timeout 1800"
            ecs-deploy --region $REGION --cluster $CLUSTER --service-name $SERVICE --image $AWS_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/mclouds-prod-ecr:$TAG --timeout 1800
workflows:
  version: 2
  buil&push:
    jobs:
      - dockerbuild:
          filters:
            branches:
              only: master
      - deployecs:
          requires:
            - dockerbuild
          filters:
            branches:
              only: master
